environment:
  RUST: stable
  matrix:
    - TARGET: x86_64-pc-windows-msvc
    - TARGET: x86_64-pc-windows-gnu
    - TARGET: i686-pc-windows-msvc
    - TARGET: i686-pc-windows-gnu
    - TARGET: x86_64-pc-windows-msvc
      RUST: nightly

install:
  - curl -sSf -o rustup-init.exe https://win.rustup.rs/
  - rustup-init.exe -y --default-host %TARGET% --default-toolchain %RUST%
  - set PATH=%PATH%;C:\Users\appveyor\.cargo\bin
  - rustc -V
  - cargo -V

build: false

test_script:
  - set RUST_BACKTRACE=1
  - cargo build --verbose
  - cargo test --verbose
  - cargo test --release --verbose
