[package]
name = "termion"
version = "1.5.1"
authors = ["ticki <Ticki@users.noreply.github.com>", "gycos <alexandre.bury@gmail.com>", "IGI-111 <igi-111@protonmail.com>"]
description = "A bindless library for manipulating terminals."
repository = "https://github.com/ticki/termion"
documentation = "https://docs.rs/termion"
license = "MIT"
keywords = ["tty", "color", "terminal", "password", "tui"]
exclude = ["target", "CHANGELOG.md", "image.png", "Cargo.lock"]

[target.'cfg(all(not(target_os = "redox"), not(windows)))'.dependencies]
libc = "0.2.8"

[target.'cfg(target_os = "redox")'.dependencies]
redox_syscall = "0.1"
redox_termios = "0.1"

[target.'cfg(target_os = "windows")'.dependencies]
widestring = "0.2.2"

[target.'cfg(target_os = "windows")'.dependencies.winapi]
version = "0.3.4"
features = ["consoleapi", "handleapi", "minwindef", "processenv", "winbase", "wincon"]
